config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, skip: [:sessions, :registrations]
  # devise_for :parents, path: 'parent', controllers: { sessions: "parents/sessions" }
  # devise_for :children, path: 'child', controllers: { sessions: "children/sessions" }

  devise_for :users, :controllers => { :sessions => 'sessions' }, :skip => :registrations
  devise_for :parents, :children #, :skip => :sessions

  unauthenticated :users do
    root 'welcome#show', as: :unauthenticated_root
  end

  # routes only for users
  authenticated :parents, lambda {|u| u.type == "Parent"} do
    root 'parents#show', as: :parent_authenticated_root
  end

  # routes only for companies
  authenticated :children, lambda {|u| u.type == "Child"} do
    root 'children#show', as: :child_authenticated_root
  end

  resource :visitors, :only => :create

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < User
  belongs_to :parent, :class_name => 'Parent'
end

app/models/parent.rb
class Parent < User
  # Returns all children under this parent
  has_many :children, :class_name => 'Child', :foreign_key => :parent_id
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :user

  serialize :recurring, Hash

  has_many :task_exceptions

  def recurring=(value)
    if RecurringSelect.is_valid_rule?(value)
      super(RecurringSelect.dirty_hash_to_rule(value).to_hash)
    else
      super(nil)
    end
  end

  def rule
    IceCube::Rule.from_hash recurring
  end

  def schedule(start)
    schedule = IceCube::Schedule.new(start)
    schedule.add_recurrence_rule(rule)

    task_exceptions.each do |exception|
      schedule.add_exception_time(exception.time)
    end

    schedule
  end

  def calendar_tasks(start)
    if recurring.empty?
      [self]
    else
      #start_date = start.beginning_of_month.beginning_of_week
      end_date = start.end_of_month.end_of_week
      schedule(start_time).occurrences(end_date).map do |date|
        Task.new(id: id, name: name, start_time: date)
      end
    end
  end

end

app/models/task_exception.rb
class TaskException < ApplicationRecord
  belongs_to :task

  validates :time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy

  # If user has no manager, she's a manager
  def parent?
    parent_id.nil?
  end

  # If user has a manager, she's a writer
  def child?
    !parent?
  end
end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :authenticate_child!

  def show

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/parent_controller.rb
class ParentsController < ApplicationController
  before_action :authenticate_parent!

  def show

  end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :authenticate_parent!




end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    def create
        rtn = super
        sign_in(resource.type.underscore, resource.type.constantize.send(:find, resource.id)) unless resource.type.nil?
        rtn
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_parent!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.fetch(:task, {})
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def create
     @visitor = Visitor.new(params.require(:visitor).permit(:email))
    @visitor.save
    respond_to do |f|
      f.html { redirect_to unauthenticated_root_path }
      f.js { render js: "$('#email_form').hide();$('.email_txt').text('Thank you for your interest')" }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    @visitor = Visitor.new
  end

  def sign_up

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end

  def meta_description(page_meta_description)
    content_for(:meta_description) { page_meta_description }
  end

  def heading(page_heading)
    content_for(:heading) { page_heading }
  end

  def humanize_boolean(input)
    input ||= ''
    case input.to_s.downcase
    when 't', 'true'
      'Yes'
    else
      'No'
    end
  end

  def css_for_boolean(input)
    if input
      'success'
    else
      'danger'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/children/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/children/show.haml
Hello Child

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <% unless key == :timedout %>
    <%= content_tag :div, class: "alert alert-dismissable alert-#{key}" do -%>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
      <%= msg %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Kidc
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}

    = action_cable_meta_tag
    %link{:href => "https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css", :rel => "stylesheet"}
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      %script{:src => "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"}
      %script{:src => "//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"}
      %script{:src => "//cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body#page-top
    = render 'partials/flash'
    = yield
    = render 'partials/google_analytics'
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = yield :javascript_includes

app/views/pages/home.html.erb
<%
 title "Yay! You're on Rails!"
 meta_description 'Meta descriptions are useful for SEO purposes.'
 heading "Yay! You're on Rails!"
%>

<div class="row">
  <div class="col-sm-8">
    <p class="lead">
      You have successfully generated this project
      with <%= link_to 'orats', 'https://github.com/nickjj/orats' %> v5.0.3.
    </p>

    <p>
      <%= image_tag 'https://badge.fury.io/rb/orats.png', alt: 'Gem badge' %>
      is the latest version.
    </p>

    <hr/>

    <h3>Learn more about Docker and this project</h3>

    <ul>
      <li>
        <%= link_to 'Learn how this application was Dockerized', 'http://nickjanetakis.com/blog/dockerize-a-rails-5-postgres-redis-sidekiq-action-cable-app-with-docker-compose' %>
      </li>
    </ul>

    <hr/>

    <h3>Want to get rid of this page?</h3>

    <p>No problem, just follow these steps:</p>

    <ul>
      <li>
        Run <code>docker-compose exec website rails d controller Pages</code>
      </li>
      <li>
        Remove the root route from <code>config/routes.rb</code>
      </li>
    </ul>
  </div>

  <div class="col-sm-4"></div>
</div>

app/views/pages/home.html.haml
- title "Yay! You're on Rails!"
- meta_description 'Meta descriptions are useful for SEO purposes.'
- heading "Yay! You're on Rails!"
.row
  .col-sm-8
    %p.lead
      You have successfully generated this project
      with #{link_to 'orats', 'https://github.com/nickjj/orats'} v5.0.3.
    %p
      = image_tag 'https://badge.fury.io/rb/orats.png', alt: 'Gem badge'
      is the latest version.
    %hr/
    %h3 Learn more about Docker and this project
    %ul
      %li
        = link_to 'Learn how this application was Dockerized', 'http://nickjanetakis.com/blog/dockerize-a-rails-5-postgres-redis-sidekiq-action-cable-app-with-docker-compose'
    %hr/
    %h3 Want to get rid of this page?
    %p No problem, just follow these steps:
    %ul
      %li
        Run
        %code docker-compose exec website rails d controller Pages
      %li
        Remove the root route from
        %code config/routes.rb
  .col-sm-4

app/views/parents/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/parents/show.haml
Hello Parent

app/views/partials/_flash.haml
- flash.each do |key, msg|
  - unless key == :timedout
    = content_tag :div, class: "alert alert-dismissable alert-#{key}" do
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"}
        ×
      = msg

app/views/partials/_google_analytics.haml
- if ENV['GOOGLE_ANALYTICS_UA'].present?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    // Enable 'Demographics and interest reports' in your analytics settings
    // ga('require', 'displayfeatures');

    // Enable 'Use enhanced link attribution' in your analytics settings
    // ga('require', 'linkid', 'linkid.js');

    ga('create', '#{ENV["GOOGLE_ANALYTICS_UA"]}', 'auto');
    ga('send', 'pageview');

app/views/partials/_google_analytics.html.haml
- if ENV['GOOGLE_ANALYTICS_UA'].present?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    // Enable 'Demographics and interest reports' in your analytics settings
    // ga('require', 'displayfeatures');

    // Enable 'Use enhanced link attribution' in your analytics settings
    // ga('require', 'linkid', 'linkid.js');

    ga('create', '#{ENV["GOOGLE_ANALYTICS_UA"]}', 'auto');
    ga('send', 'pageview');

app/views/tasks/_form.html.haml
= form_for(task) do |f|
  - if task.errors.any?
    #error_explanation
      %h2
        = pluralize(task.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - task.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .field
    = f.label :recurring
    = f.select_recurring :recurring, nil, allow_blank: true
  .actions
    = f.submit

app/views/tasks/edit.html.haml
%h1 Editing Task
= render 'form', task: @task
= link_to 'Show', @task
|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%p#notice= notice
%h1 Tasks
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @tasks.each do |task|
      %tr
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New Task
= render 'form', task: @task
= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_task_path(@task)
|
= link_to 'Back', tasks_path

app/views/welcome/_about.haml
%section#about.about.bg-primary.text-center
  .container
    .row
      .col-md-8.col-md-offset-2
        %h2.section-heading.email_txt Coming Soon! give us your email to learn more
        #email_form
          = form_for @visitor,  :remote => true do |f|
            = f.text_field :email, :placeholder => "Email"
            = f.submit "Sign up"

app/views/welcome/_contact.haml
%section#contact.contact.bg-primary
  .container
    %h2
      We
      %i.fa.fa-heart
      new friends!
    %ul.list-inline.list-social
      %li.social-twitter
        %a{:href => "#"}
          %i.fa.fa-twitter
      %li.social-facebook
        %a{:href => "#"}
          %i.fa.fa-facebook
      %li.social-google-plus
        %a{:href => "#"}
          %i.fa.fa-google-plus

app/views/welcome/_cta.haml
%section.cta
  .cta-content
    .container
      %h2
        Stop waiting.
        %br>/
        Start building.
      %a.btn.btn-outline.btn-xl.page-scroll{:href => "#contact"} Let's Get Started!
  .overlay

app/views/welcome/_download.haml
%section#download.download.bg-primary.text-center
  .container
    .row
      .col-md-8.col-md-offset-2
        %h2.section-heading Discover what all the buzz is about!
        %p Our app is available on any mobile device! Download now to get started!
        .badges
          %a.badge-link{:href => "#"}
            %img{:alt => "", :src => image_url("google-play-badge.svg")}/
          %a.badge-link{:href => "#"}
            %img{:alt => "", :src => image_url("app-store-badge.svg")}/

app/views/welcome/_features.haml
%section#features.features
  .container
    .row
      .col-lg-12.text-center
        .section-heading
          %h2 Unlimited Features, Unlimited Fun
          %p.text-muted Check out what you can do with this app theme!
          %hr/
    .row
      .col-md-4
        .device-container
          .device-mockup.iphone6_plus.portrait.white
            .device
              .screen
                / Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else!
                %img.img-responsive{:alt => "", :src => image_url("demo-screen-1.jpg")}/
              .button
                / You can hook the "home button" to some JavaScript events or just remove it
      .col-md-8
        .container-fluid
          .row
            .col-md-6
              .feature-item
                %i.icon-screen-smartphone.text-primary
                %h3 Device Mockups
                %p.text-muted Ready to use HTML/CSS device mockups, no Photoshop required!
            .col-md-6
              .feature-item
                %i.icon-camera.text-primary
                %h3 Flexible Use
                %p.text-muted Put an image, video, animation, or anything else in the screen!
          .row
            .col-md-6
              .feature-item
                %i.icon-present.text-primary
                %h3 Free to Use
                %p.text-muted As always, this theme is free to download and use for any purpose!
            .col-md-6
              .feature-item
                %i.icon-lock-open.text-primary
                %h3 Open Source
                %p.text-muted Since this theme is MIT licensed, you can use it commercially!

app/views/welcome/_footer.haml
%footer
  .container
    %p © 2017 KidCentiv. All Rights Reserved.
    -#%ul.list-inline
    -#  %li
    -#    %a{:href => "#"} Privacy
    -#  %li
    -#    %a{:href => "#"} Terms
    -#  %li
    -#    %a{:href => "#"} FAQ

app/views/welcome/_header.haml
%header
  .container
    .row
      .col-sm-7
        .header-content
          .header-content-inner
            %h1 We're here to help
            %a.btn.btn-outline.btn-xl.page-scroll{:href => "#contact"} Sign up to learn more!
      .col-sm-5
        .device-container
          .device-mockup.iphone6_plus.portrait.white
            .device
              .screen
                / Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else!
                %img.img-responsive{:alt => "", :src => image_url("demo-screen-1.jpg")}/
              .button
                / You can hook the "home button" to some JavaScript events or just remove it

app/views/welcome/_nav.haml
%nav#mainNav.navbar.navbar-default.navbar-fixed-top
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        Menu
        %i.fa.fa-bars
      %a.navbar-brand.page-scroll{:href => "#page-top"} KidCentiv
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a.page-scroll{:href => "#about"} About
        %li
          %a.page-scroll{:href => "#features"} Features
        %li
          %a.page-scroll{:href => "#contact"} Contact
    / /.navbar-collapse
  / /.container-fluid

app/views/welcome/show.haml
= render :partial => 'nav'
= render :partial => 'header'
= render :partial => 'about'
= render :partial => 'features'
= render :partial => 'features'
= render :partial => 'contact'
= render :partial => 'footer'